kafka:
  listeners:
    client: 
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    external: 
      protocol: PLAINTEXT

  controller:
    persistence:
      enabled: false
  broker: 
    persistence:
      enabled: false
  zookeeper: 
    persistence:
      enabled: false
  fullnameOverride: kafka