apiVersion: v1
kind: Service
metadata:
  name: access-node-list
  namespace: {{ $.Release.Namespace | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: access-node-list
    app.kubernetes.io/instance: {{ .Release.Name }}