deployment:
  image:
    repository: in2kizuna/broker-adapter
    # -- tag of the image to be used
    tag: v2.0.0
    # -- specification of the image pull policy
    pullPolicy: IfNotPresent
  logLevel: DEBUG
  broker:
    externalDomain: http://scorpio:9090
    internalDomain: http://scorpio:9090
 
service:
  port: 8080
  type: ClusterIP

fullnameOverride: broker-adapter