postgresql:
  
  fullnameOverride: postgis
  nameOverride: postgis

  auth:
    username: postgres
    enablePostgresUser: true
    password: postgres
    
  primary:
    persistence: 
      enabled: false
    initdb:
      scripts:
        enable.sh: |
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE EXTENSION postgis;"
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE ngb;"
  
  readReplicas:
    persistence: 
      enabled: false