apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dlt-adapter.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "dlt-adapter.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dlt-adapter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{ include "dlt-adapter.labels" . | nindent 8 }}
    spec:
      containers: 
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          env:
            - name: PRIVATE_KEY
              value: {{ .Values.deployment.privateKey }}
            - name: CONTRACT_ADDRESS
              value: "0x37532a3dbf29942d10fb8ba57dc35d2134fe494d"
          ports:
            - containerPort: {{ .Values.service.port}}
              name: http
              protocol: TCP