apiVersion: v1
kind: ConfigMap
metadata:
  name: account-registration
  namespace: {{ .Release.Namespace | quote }}
data:
  # creates the account used for the tests and transfers enough funds from the dev-default account
  init.sh: |-
    #!/bin/bash
    
    apt-get -y update; apt-get -y install curl; apt-get -y install jq;

    account=$(curl -X POST {{ .Values.blockchain.address }} --data '{"jsonrpc":"2.0", "method":"personal_importRawKey","params":["{{ .Values.blockchain.key }}", "pwd"],"id":1}' -H 'Content-Type: application/json' | jq -r '.result')
    source_ac=$(curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' -H "Content-Type: application/json" {{ .Values.blockchain.address }} | jq -r '.result' | jq -r '.[0]')
    
    curl -X POST {{ .Values.blockchain.address }} --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_sendTransaction\",\"params\":[{\"from\": \"$source_ac\", \"to\": \"$account\", \"value\":\"0xfffffffffffffff0\"}],\"id\":1}" -H "Content-Type: application/json"
