apiVersion: batch/v1
kind: Job
metadata:
  name: dome-contract
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      initContainers:
        - name: init-account
          image: ubuntu
          command:
            - /bin/bash
          args:
            - -ec
            - /bin/init.sh
          volumeMounts:
            - name: account-registration
              mountPath: /bin/init.sh
              subPath: init.sh
      containers:
        - name: contract-create
          image: quay.io/wi_stefan/dome-contract:0.0.2
          env:
            - name: PRIVATE_KEY
              value: 0x{{ .Values.blockchain.key }}
            - name: NODE_ENDPOINT
              value: {{ .Values.blockchain.address }}
            - name: NET_CHAIN_ID
              value: "1"
      restartPolicy: OnFailure
      volumes:
        - name: account-registration
          configMap:
            name: account-registration
            defaultMode: 0755
  backoffLimit: 10

