apiVersion: batch/v1
kind: Job
metadata:
  name: dome-contract
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      containers:
        - name: contract-create
          image: quay.io/digitelts/dome-contract-deploy:1.0.0
          env:
            - name: PRIVATE_KEY
              value: "0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f"
              #value: "0x09bac90daf84adc6ca0e3161e3a67c80e4a2ab79d7f55bf9b82f566e6d62ad87"
            - name: NODE_ENDPOINT
              value: http://blockchain-testnode.infra.svc.cluster.local:8545/
            - name: T_NET_CHAIN_ID
              value: "83584648538"
            - name: B_NET_CHAIN_ID
              value: "2020"
      restartPolicy: OnFailure
  backoffLimit: 10

