blockchain-connector:
  deployment:
    blockchain:
      rpcAddress: http://blockchain-testnode.infra.svc.cluster.local:8545/
      userEthereumAddress: 0x72b440177bcDfD339eF00ffF6B78c3620c09c469
      subscription:
        active: true
        eventTypes: service-catalog
        notificationEndpoint: http://blockchain-connector.consumer.svc.cluster.local:8080/notifications/dlt
    broker:
      externalDomain: http://scorpio.consumer.svc.cluster.local:9090
      internalDomain: http://scorpio.consumer.svc.cluster.local:9090
    ngsiSubscription:
      entityTypes: party
    operator:
      organizationId: did:web:consumer.org

dlt-adapter:
  deployment:
    privateKey: 0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f
    contractAddress: 0x37532a3dbf29942d10fb8ba57dc35d2134fe494d
  replicaCount: 1
  image:
    repository: quay.io/wi_stefan/dlt-adapter
    # -- tag of the image to be used
    tag: latest
    # -- specification of the image pull policy
    pullPolicy: Always
  logLevel: DEBUG
  fullnameOverride: dlt-adapter

postgresql:
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false

postgis:
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false

tm-forum-api:
  defaultConfig:
    endpointsPort: 8081
    additionalEnvVars:
      - name: LOGBACK_APPENDER
        value: CONSOLE

  apiProxy:
    service:
      type: LoadBalancer
      port: 8081