blockchain-connector:
  deployment:
    blockchain:
      userEthereumAddress: 0x72b440177bcDfD339eF00ffF6B78c3620c09c469
      subscription:
        active: true
        eventTypes: service-catalog
        notificationEndpoint: http://blockchain-connector.consumer.svc.cluster.local:8080/notifications/dlt
    privateKey: 0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f
    broker:
      externalDomain: http://scorpio.consumer.svc.cluster.local:9090
      internalDomain: http://scorpio.consumer.svc.cluster.local:9090
    ngsiSubscription:
      entityTypes: party
    operator:
      organizationId: CONSUMER

dlt-adapter:
  deployment:
    privateKey: 0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f
    contractAddress: 0x37532a3dbf29942d10fb8ba57dc35d2134fe494d
  replicaCount: 1
  image:
    repository: quay.io/wi_stefan/dlt-adapter
    # -- tag of the image to be used
    tag: latest
    # -- specification of the image pull policy
    pullPolicy: Always
  logLevel: DEBUG
  fullnameOverride: dlt-adapter

service:
  port: 8080
  type: ClusterIP

fullnameOverride: dlt-adapter

tm-forum-api:
  defaultConfig:
    endpointsPort: 8081

  apiProxy:
    service:
      type: LoadBalancer
      port: 8081