desmos:
  image:
    repository: in2workspace/in2-desmos-api
    tag: v1.0.0-snapshot
  app:
    profile: dev
    txSubscription:
      notificationEndpoint: http://desmos.consumer.svc.cluster.local:8080/api/v1/notifications/dlt
      entityTypes: service-catalog
    broker:
      provider: scorpio
      externalDomain: http://scorpio.consumer.svc.cluster.local:9090
      internalDomain: http://scorpio.consumer.svc.cluster.local:9090
    ngsiSubscription:
      notificationEndpoint: http://desmos.consumer.svc.cluster.local:8080/api/v1/notifications/broker
      entityTypes: party
    operator:
      organizationIdentifier: did:web:consumer.org
      externalDomain: http://desmos.consumer.svc.cluster.local:8080
    privateKey:
      value: "0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f"
    externalDomain: "http://external-domain.org"
    externalAccessNodesUrls:
      enableCustomUrls: true
      customUrls: ""
  fullnameOverride: desmos

dlt-adapter:
  existingSecret:
    enabled: false
    name: private-key-secret
    key: private-key
  env:
    PRIVATE_KEY: "0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f"
    DOME_EVENTS_CONTRACT_ADDRESS: ""
    RPC_ADDRESS: "http://blockchain-testnode.infra.svc.cluster.local:8545/"
    DOME_PRODUCTION_BLOCK_NUMBER: "0"
    ISS: "0x9eb763b0a6b7e617d56b85f1df943f176018c8eedb2dd9dd37c0bd77496833fe"
  replicaCount: 1
  logLevel: DEBUG
  fullnameOverride: dlt-adapter

postgresql:
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false

postgis:
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false

tm-forum-api:
  defaultConfig:
    endpointsPort: 8081
    additionalEnvVars:
      - name: LOGBACK_APPENDER
        value: CONSOLE

  apiProxy:
    service:
      type: LoadBalancer
      port: 8081
