desmos:
  app:
    eventSubscription:
      notificationEndpoint: http://desmos.consumer.svc.cluster.local:8080/notifications/dlt
      eventTypes: service-catalog
    broker:
      provider: scorpio
      externalDomain: http://scorpio.consumer.svc.cluster.local:9090
      internalDomain: http://scorpio.consumer.svc.cluster.local:9090
    ngsiSubscription:
      notificationEndpoint: http://desmos.consumer.svc.cluster.local:8080/notifications/broker
      entityTypes: party
    client:
      organizationId: did:web:consumer.org
  fullnameOverride: desmos

dlt-adapter:
  env:
    PRIVATE_KEY: 0xe2afef2c880b138d741995ba56936e389b0b5dd2943e21e4363cc70d81c89346
    DOME_EVENTS_CONTRACT_ADDRESS: 0x70d5294B2882b877484A4c4c63f8EC9B2638c07D
    RPC_ADDRESS: http://blockchain-testnode.infra.svc.cluster.local:8545/
  replicaCount: 1
  image:
    repository: quay.io/digitelts/dlt-adapter
    # -- tag of the image to be used
    tag: ""
    # -- specification of the image pull policy
    pullPolicy: Always
  logLevel: DEBUG
  fullnameOverride: dlt-adapter

postgresql:
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false

postgis:
  primary:
    persistence:
      enabled: false
  readReplicas:
    persistence:
      enabled: false

tm-forum-api:
  defaultConfig:
    endpointsPort: 8081
    additionalEnvVars:
      - name: LOGBACK_APPENDER
        value: CONSOLE

  apiProxy:
    service:
      type: LoadBalancer
      port: 8081
