deployment:
  blockchain:
    userEthereumAddress: 0x72b440177bcDfD339eF00ffF6B78c3620c09c469
    subscription:
      active: true
      eventTypes: service-catalog
      notificationEndpoint: http://blockchain-connector.consumer.svc.cluster.local:8080/notifications/dlt
  privateKey: 0x304d170fb355df65cc17ef7934404fe9baee73a1244380076436dec6fafb1e1f
  broker:
    externalDomain: http://scorpio.consumer.svc.cluster.local:9090
    internalDomain: http://scorpio.consumer.svc.cluster.local:9090
  ngsiSubscription:
    entityTypes: party
  operator:
    organizationId: CONSUMER
tm-forum-api:
  defaultConfig:
    endpointsPort: 8081
  apiProxy:
    service:
      type: LoadBalancer
      port: 8081