deployment:
  image:
    repository: quay.io/wi_stefan/dlt-adapter
    # -- tag of the image to be used
    tag: latest
    # -- specification of the image pull policy
    pullPolicy: Always
  logLevel: DEBUG

service:
  port: 8080
  type: ClusterIP

fullnameOverride: dlt-adapter