apiVersion: v1
kind: Service
metadata:
  name: {{ include "scorpio.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "scorpio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # same as scorpio, makes other config easier
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "scorpio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}