deployment:
  image:
    repository: quay.io/digitelts/dlt-adapter
    # -- tag of the image to be used
    tag: 1.2.1
    # -- specification of the image pull policy
    pullPolicy: IfNotPresent
  logLevel: DEBUG

service:
  port: 8080
  type: ClusterIP

fullnameOverride: dlt-adapter