tm-forum-api:
  defaultConfig:
    logLevel: TRACE
    image:
      tag: "0.16.0"
    additionalEnvVars:
      - name: LOGBACK_APPENDER
        value: CONSOLE
    ngsiLd:
      url: http://scorpio:9090
    contextUrl: https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld
  apiProxy:
    enabled: true