apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockchain-connector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "blockchain-connector.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "blockchain-connector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{ include "blockchain-connector.labels" . | nindent 8 }}
    spec:
      containers: 
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          env: 
            - name: SPRING_LOGGING_LEVEL_ROOT
              value: {{ .Values.deployment.logLevel }}
            - name: SPRING_R2DBC_PASSWORD
              value: {{ .Values.db.password }}
            - name: SPRING_R2DBC_USERNAME
              value: {{ .Values.db.username }}
            - name: SPRING_FLYWAY_USERNAME
              value: {{ .Values.db.username }}
            - name: SPRING_FLYWAY_PASSWORD
              value: {{ .Values.db.password }}
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://{{ .Values.db.host }}:5432/mktdb"
            - name: SPRING_FLYWAY_URL
              value: "jdbc:postgresql://{{ .Values.db.host }}:5432/mktdb"
            - name: DLT_ADAPTER_DOMAIN
              value: {{ .Values.deployment.dltAdapter.domain }}
            - name: BLOCKCHAIN_RPC_ADDRESS
              value: {{ .Values.deployment.blockchain.rpcAddress }}
            - name: BLOCKCHAIN_USER_ETHEREUM_ADDRESS
              value: {{ .Values.deployment.blockchain.userEthereumAddress }}
            - name: BLOCKCHAIN_SUBSCRIPTION_ACTIVE
              value: {{ .Values.deployment.blockchain.subscription.active | quote }}
            - name: BROKER_EXTERNAL_DOMAIN
              value: {{ .Values.deployment.broker.externalDomain }}
            - name: BROKER_INTERNAL_DOMAIN
              value: {{ .Values.deployment.broker.internalDomain }}
            - name: NGSI_SUBSCRIPTION_NOTIFICATION_ENDPOINT
              value: {{ .Values.deployment.ngsiSubscription.notificationEndpoint }}
            - name: NGSI_SUBSCRIPTION_ENTITY_TYPES
              value: {{ .Values.deployment.ngsiSubscription.entityTypes }}
            - name: BROKER_ADAPTER_DOMAIN
              value: {{ .Values.deployment.brokerAdapter.domain }}
            - name: BROKER_ADAPTER_PATHS_SUBSCRIPTIONS
              value: {{ .Values.deployment.brokerAdapter.paths.subscriptions }}
            - name: BROKER_ADAPTER_PATHS_ENTITIES
              value: {{ .Values.deployment.brokerAdapter.paths.entities }}
            - name: OPERATOR_ORGANIZATION_ID
              value: {{ .Values.deployment.operator.organizationId }}
          ports:
            - containerPort: {{ .Values.service.port}}
              name: http
              protocol: TCP